### PR TITLE
Downgrade collection 1.17.1 -> 1.15.0

### LINKED ISSUE #141: [v0.4.0] collection version conflict between the v0.4.0 and flutter_test
## Description

While installing the v0.4.0 I am getting this error:

```
Because http_mock_adapter >=0.4.0 depends on collection ^1.17.1 and every version of flutter_test from sdk depends on collection 1.17.0, http_mock_adapter >=0.4.0 is incompatible with flutter_test from sdk.
So, because adapter depends on both flutter_test from sdk and http_mock_adapter ^0.4.0, version solving failed.
```

## Steps to reproduce

Just updated the http_mock_adapter version from v0.3.3 to v0.4.0. Run "flutter pub upgrade"

## Expected behavior

No failure on resolving dependencies.

## System details

Flutter version 3.7.3 on channel stable
Dart version 2.19.2

## Additional context

Probably the v0.4.0 needs to lower down the collection package version to ^1.17.0.

### PR DESCRIPTION
**Pull request by LukaGiorgadze**
## Description

fixes #141

### CODE REVIEW

**Comment by kuhnroyal** [comment]
Please `1.15.0` otherwise this library can not be used to test on min Dio requirements.

**Comment by chunghha** [comment]
@LukaGiorgadze I just leave a comment here as requested. collection 1.6.0 is installed with flutter sdk 3.3.x. As I use the 3.7.x, I am fine with setting to ^1.6.0 in this package so I will be still able to install the 1.7.x in my projects. If you'd like to support flutter sdk 3.0.x users as well then setting to ^1.5.0 might be required.

**Comment by LukaGiorgadze** [comment]
Okay let's revert it back. Please approve once you are okay with it.

**Comment by kuhnroyal** [comment]
Thanks!

**Pull request merged**
