### PR TITLE
Update to v0.3.0

### PR DESCRIPTION
**Pull request by GiorgiBeriashvili**
## Description

This is a release candidate for version `0.3.0` of the package.

Please see the [CHANGELOG.md](https://github.com/lomsa-dev/http-mock-adapter/blob/73c69f5f21f2d4bfab80d6546d3742fc037fa174/CHANGELOG.md) file for brief summary of changes.

### CODE REVIEW

**Review by LukaGiorgadze — APPROVED** [review]

**Review by theiskaa — APPROVED** [review]

**Comment by LukaGiorgadze** [comment]
@GiorgiBeriashvili i guess it's time to merge this PR.

**Comment by GiorgiBeriashvili** [comment]
> @GiorgiBeriashvili i guess it's time to merge this PR.

Not yet, documentation remains. It's in progress and will be done by the end of the day.

**Comment by LukaGiorgadze** [comment]
> > @GiorgiBeriashvili i guess it's time to merge this PR.
> 
> Not yet, documentation remains. It's in progress and will be done by the end of the day.

Oh sorry, i just noticed that it's still `Draft` PR.

**Comment by GiorgiBeriashvili** [comment]
It's ready to be merged upon approval.

**Review by LukaGiorgadze — APPROVED** [review]

**Pull request merged**
