### PR TITLE
Match var names & ops. Null chk. Default headers.

### PR DESCRIPTION
**Pull request by ncb000gt**
## Description

Should fixe some residual issues with https://github.com/lomsa-dev/http-mock-adapter/pull/69 described below.

Match variable names didn't match the actual operation, they were relying on `!match()` and the names reflected positive matching.

Moved null check to `matches` function for less code.

Added default headers to the header check since the adapter adds them on the fetch call.

Signed-off-by: Nick Campbell <nicholas.j.campbell@gmail.com>

### CODE REVIEW

**Review by GiorgiBeriashvili — COMMENTED** [review]
It is more readable now, and the default headers is a nice touch, thank you!

I was thinking that the variable names could be more consistent (one ends with `Matches` and the others with `Match`) and perhaps `matching` prefix such as `matchingHeaders`?

The former case regarding consistency should change I think, and the latter is up to your decision as it was merely a suggestion. What do you think?

**Comment by ncb000gt** [comment]
Yea. I thought about this but attempted to keep them consistent with how I might read something. `matching` wasn't quite working when I tried to "read" what the variable meant. Thinking about it again though the checks tell you something about the past so maybe using the `Matched` postfix instead would be best:
* `requestDataMatched`
* `headersMatched`
* `queryParametersMatched`

Thoughts?

**Comment by GiorgiBeriashvili** [comment]
> Yea. I thought about this but attempted to keep them consistent with how I might read something. `matching` wasn't quite working when I tried to "read" what the variable meant. Thinking about it again though the checks tell you something about the past so maybe using the `Matched` postfix instead would be best:
> 
>     * `requestDataMatched`
> 
>     * `headersMatched`
> 
>     * `queryParametersMatched`
> 
> 
> Thoughts?

Sounds good to me! I will approve the PR as soon as the changes will be applied.

**Review by GiorgiBeriashvili — APPROVED** [review]

**Comment by GiorgiBeriashvili** [comment]
> Landed the changes we discussed.

Both #78 and #79 is approved by me. Let's see if @campfire5 has something to add, he will review the PRs soon and then we will merge the changes.

**Review by campfire5 — APPROVED** [review]

**Review by LukaGiorgadze — APPROVED** [review]

**Pull request merged**
