### PR TITLE
Add isA<T> & FormData matchers

### PR DESCRIPTION
**Pull request by kuhnroyal**
## Description

* export `Matcher` base class for easy custom matchers
* add `FormDataMatcher`
* add `IsAMatcher`
* add tests

### CODE REVIEW

**Comment by kuhnroyal** [comment]
CC @LukaGiorgadze @GiorgiBeriashvili @campfire5

**Comment by LukaGiorgadze** [comment]
@theiskaa

**Comment by theiskaa** [comment]
Just change what I commented, other things are ok for me. But should wait for @GiorgiBeriashvili's review.

**Review by theiskaa — CHANGES_REQUESTED** [review]
Hey! Thanks, man! 
Just change what I commented, other things are ok for me. But should wait for @GiorgiBeriashvili's review.

**Review by GiorgiBeriashvili — DISMISSED** [review]
Looks pretty good to me. I appreciate thorough tests.

**Review by LukaGiorgadze — APPROVED** [review]
Nice! Thank you!
Just a small code styling suggestion by @theiskaa and ready to merge.

**Review by theiskaa — APPROVED** [review]
Approved, Thank you so much for contribution!

**Pull request merged**
