### PR TITLE
Future/response-delay

### PR DESCRIPTION
**Pull request by theiskaa**
## Description

Resolves: #106 

**One point:** If you gave a delayed value of more than 0 seconds then it will fail until you didn't give await to your mock repsonse. 
Example:
```dart
  await dioAdapter.onGet(
      path,
      (request) => request.reply(200, {'message': 'Successfully mocked GET!'}),
      queryParameters: queryParameters,
      delay: Duration(seconds: 5),
    );
```

### CODE REVIEW

**Comment by GiorgiBeriashvili** [comment]
I don't know if it's best to introduce `async` methods, as it might complicate the API and result in annoying warnings from linters about unawaited calls such as now (the reason why the CI jobs failed).

I'll give it a bit more thought, maybe it doesn't really matter in the end and it's worth it.

**Comment by campfire5** [comment]
> I don't know if it's best to introduce `async` methods, as it might complicate the API and result in annoying warnings from linters about unawaited calls such as now (the reason why the CI jobs failed).
> 
> I'll give it a bit more thought, maybe it doesn't really matter in the end and it's worth it.

Agree to @GiorgiBeriashvili  no async methods, we need think something else out.

**Comment by campfire5** [comment]
But in the end it is not that needed for now.

**Comment by theiskaa** [comment]
Okay then, what we should do now? Could I close PR?

**Comment by LukaGiorgadze** [comment]
Closing PR due to inactivity/unnecessary feature.
Re-open if needed.

**Comment by ElteHupkes** [comment]
I had another crack at this in #126 that I believe implements this without any breaking changes, if you'll have a look.

**Pull request closed without merging**
