### PR TITLE
Fix several response problems

### PR DESCRIPTION
**Pull request by kuhnroyal**
This PR attempts to address several problems discovered in #76.

1. The static internal instances of `DioAdapter` and `DioInterceptor` exist to allow building chains of requests. This is a great feature but in its current design breaks when running parallel tests. To mitigate this problem I changed the implementation to use Dart builder/chaining (`adapter..onGet()..onGet()`) and a response handler syntax.

2. When sending 2 or more requests that match the same `RequestMatcher`, then the response can not be reused because the stream has already been closed when sending the first response. To avoid this the `RequestHandler` now has a map of statusCode to a function that returns a `Responsable` - this allows to construct a new response every time.

This seems to work well in all kinds of scenarios that previously failed.

### CODE REVIEW

**Comment by kuhnroyal** [comment]
CC @LukaGiorgadze @GiorgiBeriashvili @campfire5

**Comment by mb-genvis** [comment]
this would be great to be introduced soon, we are facing the same problem. 

How long till you can push this or do you have some examples for a workaround in the interim?

**Comment by kuhnroyal** [comment]
Yea, would be great if this can be released as a new minor and afterwards there could be a 1.0.0-nullsafety version.

**Comment by GiorgiBeriashvili** [comment]
@kuhnroyal Very beneficial changes, thank you very much!

I have a question regarding `handler`, - is there a reason why it's an optional parameter? Perhaps it could be a positional parameter instead since it's always provided?

> this would be great to be introduced soon, we are facing the same problem.
> 
> How long till you can push this or do you have some examples for a workaround in the interim?

Thank you for your patience. @kuhnroyal solved this wonderfully as I see it, I advocate that this should be merged into `develop` branch quite soon.

> Yea, would be great if this can be released as a new minor and afterwards there could be a 1.0.0-nullsafety version.

I was thinking on `v0.2.0` after this (and maybe some other minor changes later) and then the `nullsafe` version as you pointed out.

**Comment by kuhnroyal** [comment]
Yes, before the changes it actually was optional in `onRoute` but that has changes. I renamed the parameter to `callback` and defaulted to naming the callback parameter `request`. That reflects the intent a little better. Basically you call `reply` on the `request` to create a `Response`.

**Review by GiorgiBeriashvili — APPROVED** [review]
Approved by me.

I will merge soon if no one else reviews the PR.

**Comment by kuhnroyal** [comment]
My last push broke the OpenAPI generator build where I started using this great library to test the Dart generator 😔 https://github.com/OpenAPITools/openapi-generator/pull/8870

**Comment by GiorgiBeriashvili** [comment]
> My last push broke the OpenAPI generator build where I started using this great library to test the Dart generator pensive [OpenAPITools/openapi-generator#8870](https://github.com/OpenAPITools/openapi-generator/pull/8870)

The commit where you changed optional parameter to positional parameter? Seems weird if that's the case, as the functionality should remain the same.

Is there any way I can help?

**Comment by kuhnroyal** [comment]
Nah it's all good, the PR is up to freeze this to my latest commit until a version is released.

Well the method signature changed and now has a required and non-named parameter, so that's always a compile error :)

**Pull request merged**
