### PR TITLE
Remove recursive export of matchers.dart

### PR DESCRIPTION
**Pull request by Hannnes1**
# Pull Request Template

## Your checklist for this pull request

Please review the [guidelines for contributing](https://github.com/lomsa-dev/http-mock-adapter/blob/develop/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a `feature`/`bugfix` branch** (right side). Don't request your `main` or `develop`!
- [x] Make sure you are making a pull request against the **`develop` branch** (left side). Also, you should start *your branch* off *our `develop`*.
- [x] Make sure that you add reviewers, assignees, labels, projects, milestones and linkes issues to the pull request as you see fit.
- [x] Check the commit's or even all commits' message styles to match our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.

**Tip**: Delete everything but the following section that contains the description of the pull request.

---

## Description

This pull request removes a recursive export of `matchers.dart`, since it causes [freezed](https://pub.dev/packages/freezed) to fail when generating code. See this issue for reference: https://github.com/rrousselGit/freezed/issues/445

### CODE REVIEW

**Comment by bcardoso27** [comment]
Hi @Hannnes1, why was this pull request was closed without being merged?
Was looking forward to it as I suffer from the same error you were trying to solve.

**Comment by Hannnes1** [comment]
I'm not sure. I hadn't noticed until now... I can open a new one.

**Comment by Hannnes1** [comment]
It seems like I accidentally removed my branch. I'll fix it shortly

**Comment by Hannnes1** [comment]
A new pull request has been opened at https://github.com/lomsa-dev/http-mock-adapter/pull/133

**Pull request closed without merging**
